### ISSUE TITLE
Character Overwriting another character's custom Graffiti

### ISSUE THREAD

**Issue by Fraisk** [SGiygas/CrewBoom#10]
This issue only persists when replacing existing in game characters that share the same personal graffiti texture. [Like Frank and Flesh Prince, Futurism and DJ Cyber, and Red and Red Felix]

For this example I'll use [Corn](https://gamebanana.com/mods/469318) Over Flesh Prince and [Scout](https://gamebanana.com/mods/465514) over Frank,

This is what the small graffiti looks like when corn sprays it:

![Screenshot 2023-10-30 212918](https://github.com/SGiygas/CrewBoom/assets/32005929/5ee9e1ee-4694-4b3f-8ff8-e911066509a5)

Seems all good! Now lets see what Scout's graffiti looks like:

![Screenshot 2023-10-30 214400](https://github.com/SGiygas/CrewBoom/assets/32005929/0495f293-5850-4648-976f-a51322d9aa52)

Yeah, oof. You can tell that's scout's graffiti because his graffiti's name is different compared to Corn's. With Corn's graffiti just being called Graffiti and Scout's Graffiti being named Battin' A Thousand

![Screenshot 2023-10-30 213109](https://github.com/SGiygas/CrewBoom/assets/32005929/81173f11-0453-48a8-a4bc-cab950412dea)

**Comment by SGiygas** [comment]
This is a limitation with the base game that I am not willing to mess with.
As such this won't be fixed.
You can make sure that every character has their own graffiti by adding them as their own slot by using "None" in the character json.

**Comment by SGiygas** [comment]
This is a limitation with the base game that I am not willing to mess with.
As such this won't be fixed.
You can make sure that every character has their own graffiti by adding them as their own slot by using "None" in the character json.
