### ISSUE TITLE
Logo doesn't appear properly on resolutions other than 1080p

### ISSUE THREAD

**Issue by ActualMandM** [SGiygas/CrewBoom#11]
When playing BRC with resolutions other than 1920x1080, the CrewBoom logo on the main menu will not appear in the top left as it normally does.

1920x1080:
![2023-11-16_17-21-59_Bomb_Rush_Cyberfunk](https://github.com/SGiygas/CrewBoom/assets/15317421/bd082cbc-00d2-44de-a9e4-9273172ab5e7)

2560x1440:
![2023-11-16_17-20-47_Bomb_Rush_Cyberfunk](https://github.com/SGiygas/CrewBoom/assets/15317421/f09d9058-4d41-4e03-8845-aa9ba9f6830e)

3440x1440:
![2023-11-16_17-18-05_Bomb_Rush_Cyberfunk](https://github.com/SGiygas/CrewBoom/assets/15317421/b68e14ce-d20b-426b-b488-ad31a2a506fd)

1280x800
![2023-11-16_17-24-03_Bomb_Rush_Cyberfunk](https://github.com/SGiygas/CrewBoom/assets/15317421/71201bf4-5465-4191-b27e-de8b3bcb1989)

**Comment by SGiygas** [comment]
Fixed with the new patch 3.2.3!

**Comment by ActualMandM** [comment]
Perfect, thanks!

![2023-11-19_15-11-13_Bomb_Rush_Cyberfunk](https://github.com/SGiygas/CrewBoom/assets/15317421/089283f9-e7bf-4d8d-a283-3903e94395c2)
