### ISSUE TITLE
character description for BRC prefab froze up.

### ISSUE THREAD

**Issue by Hiderlink20** [SGiygas/CrewBoom#3]
![Screenshot (134)](https://github.com/SGiygas/CrewBoom/assets/69734116/5599237c-e996-430e-96a5-1bb0a3af9c4d)

So, I went to set up my meshes for my model and then, after setting some of the materials and items, I decided that I wanted to remove one of the meshes.  I clicked on one of the meshes in the middle of the renderers list and set it to none.  That was what caused the character definitions tab to glitch up and freeze like this.  I can't change or click on anything to change it, but I could click the 3 dots and reset it to a point where all the information was default options which is ok.  The model still had the materials that I put on them manually before resetting.  I just thought I'd point out this glitch if you had not seen it before.  What I did was that I set my meshes in the renderers tab, clicked on the outfits to drag and drop materials and then set one of the materials in the middle to none to get this glitch.

**Comment by SGiygas** [comment]
This was already fixed in [v2.4.1](https://github.com/SGiygas/CrewBoom/releases/tag/v2.4.1)
Please use the latest Unity Project from that release
