### ISSUE TITLE
Game crashes upon load

### ISSUE THREAD

**Issue by snivez-git** [SGiygas/CrewBoom#4]
I went through all of the steps correctly, and the editor even said i was fine to export the model.
However, when I launched the game modded, the game would CTD with this error message:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) Reptile.CharacterVisual.DMD<Reptile.CharacterVisual::Init>(Reptile.CharacterVisual,Reptile.Characters,UnityEngine.RuntimeAnimatorController,bool,single)
CrewBoom.Patches.ConstructorCreateVisualPatch.Prefix (Reptile.Characters character, UnityEngine.RuntimeAnimatorController controller, System.Boolean IK, System.Single setGroundAngleLimit, Reptile.CharacterVisual& __result) (at <509de1ab543a4ecb8b125dab33d09d0e>:0)
(wrapper dynamic-method) Reptile.CharacterConstructor.DMD<Reptile.CharacterConstructor::CreateNewCharacterVisual>(Reptile.CharacterConstructor,Reptile.Characters,UnityEngine.RuntimeAnimatorController,bool,single)
Reptile.Player.SetCharacter (Reptile.Characters setChar, System.Int32 setOutfit) (at <973b3634b5674d37814fb9e58e20aa40>:0)
(wrapper dynamic-method) Reptile.Player.DMD<Reptile.Player::Init>(Reptile.Player,Reptile.CharacterConstructor,Reptile.Characters,int,Reptile.PlayerType,Reptile.MoveStyle,Reptile.Crew)
Reptile.WorldHandler.InitPlayer (Reptile.Player player, Reptile.Characters character, System.Int32 outfit, Reptile.PlayerType playerType, Reptile.MoveStyle moveStyleEquipped, Reptile.Crew crew) (at <973b3634b5674d37814fb9e58e20aa40>:0)
Reptile.WorldHandler.InitPlayerObject (Reptile.Player player, Reptile.Characters character, System.Int32 outfit, Reptile.MoveStyle moveStyleEquipped, Reptile.Crew crew) (at <973b3634b5674d37814fb9e58e20aa40>:0)
Reptile.StageManager.SetupWorldHandler (UnityEngine.GameObject worldHandlerPrefab, UnityEngine.GameObject wantedManagerPrefab, Reptile.Stage newStage, Reptile.Stage prevStage, Reptile.DownloadableContentItem characterDownloadableContent) (at <973b3634b5674d37814fb9e58e20aa40>:0)
Reptile.StageManager.SetupStage (Reptile.Stage prevStage, Reptile.Stage newStage, Reptile.DownloadableContentItem characterDownloadableContent) (at <973b3634b5674d37814fb9e58e20aa40>:0)
Reptile.BaseModule.SetupNewStage (Reptile.Stage previousStage, Reptile.Stage newStage) (at <973b3634b5674d37814fb9e58e20aa40>:0)
UnityEngine.Debug:LogException(Exception)
Reptile.PlatformSteam:HandleExceptionInGame(Exception)
Reptile.Core:HandleExceptionInGame(Exception)
Reptile.BaseModule:HandleExceptionInStageSetup(Exception)
Reptile.BaseModule:SetupNewStage(Stage, Stage)
Reptile.BaseModule:HandleLoadStageInstruction(LoadStageASyncInstruction)
Reptile.BaseModule:HandleStageTransition(ASceneSetupInstruction)
Reptile.<OnSceneSetupCoroutineEnded>d__86:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by SGiygas** [comment]
Pasting a crash log doesn't really tell me anything, there could be multiple reasons for it crashing.
Standalone the plugin does not crash so it is likely another mod/plugin you're using conflicting with it.

**Comment by snivez-git** [comment]
I only have crewboom installed standalone

**Comment by SGiygas** [comment]
You didn't really provide me any more information, so I can only guess but
maybe this is the cause of your crash: https://github.com/SGiygas/CrewBoom/wiki/Troubleshooting#the-game-crashes-with-an-error-for-charactervisualinit
