### ISSUE TITLE
Alternate Outfit Help

### ISSUE THREAD

**Issue by DJCraneaJr** [SGiygas/CrewBoom#7]
![image](https://github.com/SGiygas/CrewBoom/assets/139004048/a6a4fc90-41a4-45c6-9969-acbe4cc3aca3)
There is no instruction on what exactly to do here for the alternate outfits. It just tells you to DO it. How exactly?

**Comment by SGiygas** [comment]
Please read [the documentation about how to make outfits](https://github.com/SGiygas/CrewBoom/wiki/Creating-a-custom-character#outfits)

And don't use the issues section as a support area please. It's meant for reporting bugs and issues with the code of the plugin.

**Comment by DJCraneaJr** [comment]
oh, alright, sorry
