### ISSUE TITLE
New Update Causing this or what?

### ISSUE THREAD

**Issue by FlyingBlooper** [SGiygas/CrewBoom#8]
I can't see my character when I do a cypher. Their graffiti is there from me when I was using the older custom char loader but they just aren't there for cyphers. I'm assuming I did everything correctly so IDK if this was caused my the new update or not.

**Comment by SGiygas** [comment]
I have already tested the new patch and Crew Boom works as intended.
You are likely using an older character bundle made for Crew Boom v2.2.2 and using CharacterAPI and BRCCCLoader.

Please refer to the [troubleshooting page](https://github.com/SGiygas/CrewBoom/wiki/Troubleshooting)

This issue section is for **bugs and issues with the code**, not troubleshooting the plugin. Please refrain from opening issues that are too vague, too specific to your situation or unrelated to the actual code for the plugin.

**Comment by FlyingBlooper** [comment]
Probably was character api being on. I gotta test that
